name: UltraBan
version: 1.1.1
author: SinixSpielt
main: de.sinixspielt.ultraban.UltraBan

commands:
  ban:
    description: Ban a Player
  unban:
    description: Unban a Player
  kick:
    description: Kick a Player from Server
  tempban:
    description: Ban a Player for Time from Server